// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatLO9Zgfdlefgm9voRJ8iqvnutRk3dg0',
    appId: '1:64237784026:web:068c98c108c0ed7ef60ee3',
    messagingSenderId: '64237784026',
    projectId: 'bugsafe-v1-prueba',
    authDomain: 'bugsafe-v1-prueba.firebaseapp.com',
    storageBucket: 'bugsafe-v1-prueba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl-dJGrVrYZhAQBRa9BihqMBL3gq3g1_8',
    appId: '1:64237784026:android:b197d408b1a19e15f60ee3',
    messagingSenderId: '64237784026',
    projectId: 'bugsafe-v1-prueba',
    storageBucket: 'bugsafe-v1-prueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntCOh24MjZ5j_OYIfTaFHgq5I18H2Uqs',
    appId: '1:64237784026:ios:4cccb18b4e21fa1cf60ee3',
    messagingSenderId: '64237784026',
    projectId: 'bugsafe-v1-prueba',
    storageBucket: 'bugsafe-v1-prueba.firebasestorage.app',
    iosBundleId: 'com.example.bugsafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntCOh24MjZ5j_OYIfTaFHgq5I18H2Uqs',
    appId: '1:64237784026:ios:4cccb18b4e21fa1cf60ee3',
    messagingSenderId: '64237784026',
    projectId: 'bugsafe-v1-prueba',
    storageBucket: 'bugsafe-v1-prueba.firebasestorage.app',
    iosBundleId: 'com.example.bugsafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatLO9Zgfdlefgm9voRJ8iqvnutRk3dg0',
    appId: '1:64237784026:web:89eca192d8085ee4f60ee3',
    messagingSenderId: '64237784026',
    projectId: 'bugsafe-v1-prueba',
    authDomain: 'bugsafe-v1-prueba.firebaseapp.com',
    storageBucket: 'bugsafe-v1-prueba.firebasestorage.app',
  );

}